version: '3.8'
services:
  # Admin portal
  angular-portal:
    container_name: angular-portal
    build:
      context: ./services/admin-portal
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/admin-portal:/app
      - angular-node-modules:/app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api-gateway
  # Customer portal
  react-portal:
    container_name: react-portal
    build:
      context: ./services/customer-portal
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/customer-portal:/app
      - react-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api-gateway
    ports:
      - '5173:5173'
  # Gateway container
  api-gateway:
    container_name: api-gateway
    build: ./services/api-gateway
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - JAVA_OPTS=-Xmx512m -Xms256m
    ports:
      - "8765:8765"
    depends_on:
      - eureka-server
  # Eureka container
  eureka-server:
    container_name: eureka-server
    build: ./services/eureka-server
    ports:
      - "8761:8761"
  # Accounts-transactions container
  accounts-transactions:
    volumes:
      - ~/.aws:/root/.aws
    container_name: accounts-transactions
    build: ./services/accounts-transactions/accounts-service
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - api-gateway
      - accounts-db
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://accounts-db:5432/AccountsService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JAVA_OPTS=-Xmx512m -Xms256m
  # Branches container
#  branches:
#    container_name: branches
#    build: ./services/branches
#    ports:
#      - "8060:8060"
#    depends_on:
#      - eureka-server
#      - api-gateway
#      - branches-db
#    environment:
#      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://branches-db:5432/branch_service_db
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SECRET_KEY=UiynOe89DRPIBdPzuyiQ90FN4skkGOkGUO+aqW8ks3c=
#      - JAVA_OPTS=-Xmx512m -Xms256m
  # Users container
  users:
    container_name: users
    build: ./services/user-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - api-gateway
      - users-db
    volumes:
      - ~/.aws:/root/.aws
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://users-db:5432/users_service_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JAVA_OPTS=-Xmx512m -Xms256m
  # Cards/Loans container
#  cards-loans:
#    container_name: cards-loans
#    build: ./services/cards-loans
#    ports:
#      - "8070:8070"
#    depends_on:
#      - eureka-server
#      - api-gateway
#      - cards-loans-db
#    environment:
#      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://cards-loans-db:5432/cards_loans_db
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SECRET_KEY=UiynOe89DRPIBdPzuyiQ90FN4skkGOkGUO+aqW8ks3c=
#      - JAVA_OPTS=-Xmx512m -Xms256m

  users-db:
    container_name: users-db
    image: postgres:latest
    environment:
      POSTGRES_DB: users_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - users-db-data:/var/lib/postgresql/data
      - ./user-service-init:/docker-entrypoint-initdb.d

#  cards-loans-db:
#    container_name: cards-loans-db
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: cards_loans_db
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - cards-loans-db-data:/var/lib/postgresql/data
#      - ./cards-loans-init:/docker-entrypoint-initdb.d

#  branches-db:
#    container_name: branches-db
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: branch_service_db
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - branches-db-data:/var/lib/postgresql/data
#      - ./branches-init:/docker-entrypoint-initdb.d

  accounts-db:
    container_name: accounts-db
    image: postgres:latest
    environment:
      POSTGRES_DB: AccountsService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
     - accounts-db-data:/var/lib/postgresql/data
     - ./accounts-transactions-init:/docker-entrypoint-initdb.d


volumes:
  accounts-db-data:
  branches-db-data:
  users-db-data:
  cards-loans-db-data:
  angular-node-modules:
  react-node-modules:

networks:
  default:
    name: ssb-network
    driver: bridge