server:
  port: 8000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operationsSorter: method

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}
#    preferIpAddress: true

spring:
  jmx:
    enabled: true
  application:
    name: accounts-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  profiles:
    active: default
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/AccountsService}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:9557}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      jakarta.persistence.lock.timeout: 5000
      jakarta.persistence.query.timeout: 5000
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time-zone: UTC
        ddl-auto: update
        default_batch_fetch_size: 100
        order_updates: true
        order_inserts: true
        hbm2ddl:
          auto: validate
        transaction:
          jdbc_timeout: 5000
          isolation:
            level: serializable

logging:
  level:
    org.springframework: INFO
    com.securesentinel.accounts: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus,health,info'  # Expose 'prometheus' for metrics
  metrics:
    export:
      prometheus:
        enabled: true