version: '3.8'
services:
  accounts-service:
    image: accounts-service:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/AccountsService
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 9557
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - db
      - eureka-server

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: AccountsService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9557
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d/

  eureka-server:
    image: eureka-server:latest
    ports:
      - "8761:8761"