spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: branch-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/branch-service}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format_sql: true

server:
  port: 8060
  error:
    include-message: always

springdoc:
  api-docs:
    enabled: true
swagger-ui:
  enabled: true
  operationSorter: method

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
#     hostname: ${HOSTNAME:null}

h2:
  console:
    enabled: true

main:
  allow-bean-definition-overriding: true

logging:
  level:
    root: INFO

jwt:
  secret-key: ${JWT_SECRET_KEY}
