# Build Stage
FROM node:20 as build-stage
COPY package*.json /app/
WORKDIR /app
RUN npm install
COPY . .
RUN npm run build -- --output-path=./dist/secure-sentinel-bank-angular-frontend/browser

# Nginx Stage
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=build-stage /app/dist/secure-sentinel-bank-angular-frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 81

CMD ["nginx", "-g", "daemon off;"]
