spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: user-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SERVICE_USERNAME}
    password: ${MAIL_SERVICE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  datasource:
    #    url: jdbc:postgresql://free-user-instance.cnoyci44cqtj.us-east-1.rds.amazonaws.com:5432/user_service_db
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    appUser:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "http://localhost:8085/login/oauth2/code/{registrationId}"
            client-name: Google
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8085
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
#     hostname: ${HOSTNAME:null}
logging:
  level:
    root: INFO
    com.smoothstack: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
